### PR TITLE
Review changes 

### PR DESCRIPTION
**Pull request by Rohan-RPJ**

### CODE REVIEW

**Review by FullBinaryAlchemist — COMMENTED** [review]
Clicking review button generates an error? @Rohan-RPJ 

Other than that, looks fine to me

**Comment by Rohan-RPJ** [comment]
Examine all the changes and let me know if something is not as per the requirement .
Lastly if all is well then merge the requested changes and see the same in your browser

**Review by FullBinaryAlchemist — COMMENTED** [review]
The review count doesn't update when back is pressed after just pressing next on all the words and not reviewing them. The count stays fixed at 5 and gets updated only once the review is done.

**Review by FullBinaryAlchemist — CHANGES_REQUESTED** [review]
image
@Rohan-RPJ Getting error when clicking the learn from sidebar

**Comment by Rohan-RPJ** [comment]
Files modified

**Comment by FullBinaryAlchemist** [comment]
> Files modified

What was? Can't see any changes on Github

**Review by Rohan-RPJ — COMMENTED** [review]
Reviewed

**Pull request merged**
